### PR TITLE
wrap with try catch so it does not fail

### PR DESCRIPTION
**Pull request by rjacobsen2012**
Without the try/catch, it will fail in a non laravel environment in console

### CODE REVIEW

**Comment by ssi-anik** [comment]
Just asking, what's the point of adding `try...catch` block?

**Comment by rjacobsen2012** [comment]
I was doing some debugging. Never meant to put it in a real pull request. Apologies.

**Comment by ssi-anik** [comment]
You can still close the PR.

**Comment by rjacobsen2012** [comment]
I dont seem to have permission, or I would have.

**Pull request closed without merging**
